### PR TITLE
Merge pull request from harisdev-netizen/haris

### PR DESCRIPTION
**Pull request by harisdev-netizen**
PR for contributing

### CODE REVIEW

**Comment by harisdev-netizen** [comment]
I have added a new JavaScript problem to (L-A).

**Review by devvsakib — APPROVED** [review]
Thank you

**Comment by harisdev-netizen** [comment]
@devvsakib should I keep contributing by adding new problems?

**Comment by devvsakib** [comment]
Of course you can @harisdev-netizen

**Comment by devvsakib** [comment]
in open-source project, there are no limit for contribution

**Comment by harisdev-netizen** [comment]
Okay thank you @devvsakib for the heads up. I will keep contributing.

**Pull request merged**
