### PR TITLE
Added:  2 JS Code  

### PR DESCRIPTION
**Pull request by SjxSubham**
1. Added `Reverse Nodes in k-group`  in (L-I) folder and it's `README.md` file
2. Added `Unique Paths`  in (L-A) folder and it's  `README.md` file

### CODE REVIEW

**Review by devvsakib — CHANGES_REQUESTED** [review]
Please read doc before making PR

**Comment by SjxSubham** [comment]
> Please read doc before making PR

will you Please tell me what thing should I change?? or i have to add One more xtra problem?

**Review by devvsakib — COMMENTED** [review]
It's a JavaScript problem-solving repository. Why you are adding solution with C++ ?

**Comment by SjxSubham** [comment]
> It's a JavaScript problem-solving repository. Why you are adding solution with C++ ?

wait, i will make the change ASAP

**Comment by devvsakib** [comment]
yeah

**Comment by SjxSubham** [comment]
> yeah

now check it... and inform me ,all are good? or i have to change something else...

**Pull request closed without merging**
